Feat/classical bits
SnowflurrySDK/Snowflurry.jl pull request #319
Opened 2023-12-13 20:22 UTC by fSosaRey

2023-12-14 17:00 UTC, caffeine-storm requested changes

2023-12-14 17:00 UTC, caffeine-storm commented on src/anyon/qpu_interface.jl
>              params = Dict{String,Real}()
`params` doesn't seem to be used anywhere... we can remove it.
```suggestion
```

2023-12-14 17:03 UTC, caffeine-storm approved these changes

2023-12-21 20:40 UTC, plerouxanyon commented
I have no idea why the MacOS check is hanging. Googling around, it seems to come up that the MacOS runners sometimes hangs, but I haven't seen any fixes. We are not yet running any Snowflurry code at that point, so I am confident that it's not us.

2024-01-04 16:23 UTC, caffeine-storm approved these changes

2024-01-04 23:51 UTC, merged