feat: CI with Thunderhead
SnowflurrySDK/Snowflurry.jl pull request #355
Opened 2024-01-25 19:36 UTC by alireza-najafi

The CI.yml workflow now has a new job to run the tutorials on the Thunderhead server. This job runs on a self-hosted runner with label "thunderhead".

2024-01-25 19:43 UTC, plerouxanyon requested changes
The following files still contain references to `ANYON_QUANTUM_*` variables.

* docs/src/tutorials/advanced/async_jobs.md
* docs/src/tutorials/anyon_qpu.md
* docs/src/getting_started.md

I can update them if you want.

2024-01-25 19:45 UTC, plerouxanyon commented on .github/workflows/CI.yml
> +    environment: thunderhead-dev
I don't think this is the intended use of `environment`. This script doesn't deploy anything, so shouldn't have an `environment`.

2024-01-26 15:54 UTC, plerouxanyon commented on .github/workflows/CI.yml
> +    environment: thunderhead-dev
I've had a look, and GitHub doesn't seem to have a way to scope secrets in another way. I think we should keep this, but add a comment on why we are using the environment in a non-standard way.

2024-01-29 20:43 UTC, fSosaRey approved these changes

2024-01-29 20:45 UTC, plerouxanyon approved these changes

2024-01-29 20:45 UTC, merged